question_data = [
  {"text": "The Sun rises in the East.", "answer": "True"},
  {"text": "The human body has more red blood cells than white blood cells.", "answer": "True"},
  {"text": "Mercury is the smallest planet in our solar system.", "answer": "True"},
  {"text": "The Sahara is the coldest desert on Earth.", "answer": "False"},
  {"text": "The human tongue has different zones for taste types.", "answer": "False"},
  {"text": "Penguins live in the Arctic.", "answer": "False"},
  {"text": "The speed of light is faster than the speed of sound.", "answer": "True"},
  {"text": "All mammals lay eggs.", "answer": "False"},
  {"text": "The chemical formula of water is H2O.", "answer": "True"},
  {"text": "Jupiter is known as the Red Planet.", "answer": "False"},
  {"text": "The human heart has four chambers.", "answer": "True"},
  {"text": "Neutron stars are so dense that a sugar-cube sized amount would weigh billions of tons.", "answer": "True"},
  {"text": "The Andromeda Galaxy is moving away from the Milky Way.", "answer": "False"},
  {"text": "Quantum entanglement allows particles to affect each other instantly over any distance.", "answer": "True"},
  {"text": "DNA stands for Deoxyribonucleic Acid.", "answer": "True"},
  {"text": "Absolute zero is the hottest possible temperature.", "answer": "False"},
  {"text": "Antarctica is considered a desert.", "answer": "True"},
  {"text": "The strong nuclear force is weaker than the gravitational force.", "answer": "False"},
  {"text": "The Amazon Rainforest produces 20% of Earth's oxygen.", "answer": "False"},
  {"text": "Tungsten has the highest melting point of all pure metals.", "answer": "True"}
]