question_data = [
  {"text": "The Sun rises in the East.", "answer": "True"},
  {"text": "A triangle has three sides.", "answer": "True"},
  {"text": "Humans need oxygen to survive.", "answer": "True"},
  {"text": "The capital of France is Berlin.", "answer": "False"},
  {"text": "Fish can breathe underwater.", "answer": "True"},
  {"text": "The Earth is flat.", "answer": "False"},
  {"text": "Dogs are mammals.", "answer": "True"},
  {"text": "The human body has one heart.", "answer": "True"},
  {"text": "The Atlantic Ocean is larger than the Pacific Ocean.", "answer": "False"},
  {"text": "A year has 12 months.", "answer": "True"},
  {"text": "There are 60 minutes in an hour.", "answer": "True"},
  {"text": "The largest continent is Asia.", "answer": "True"},
  {"text": "A square has five sides.", "answer": "False"},
  {"text": "Spiders have eight legs.", "answer": "True"},
  {"text": "Water freezes at 0°C.", "answer": "True"},
  {"text": "Birds can fly because they have hollow bones.", "answer": "True"},
  {"text": "The moon is made of cheese.", "answer": "False"},
  {"text": "Elephants are the largest land animals.", "answer": "True"},
  {"text": "Bananas are naturally red.", "answer": "False"},
  {"text": "Humans have two lungs.", "answer": "True"},
  {"text": "The human brain is about 75% water.", "answer": "True"},
  {"text": "Lightning never strikes the same place twice.", "answer": "False"},
  {"text": "Sharks have no bones.", "answer": "True"},
  {"text": "The chemical symbol for gold is Ag.", "answer": "False"},
  {"text": "Venus is the closest planet to the Sun.", "answer": "False"},
  {"text": "The Great Barrier Reef is located in Australia.", "answer": "True"},
  {"text": "A leap year occurs every 5 years.", "answer": "False"},
  {"text": "Octopuses have blue blood.", "answer": "True"},
  {"text": "Sound travels faster in air than in water.", "answer": "False"},
  {"text": "The human body has more red blood cells than white blood cells.", "answer": "True"},
  {"text": "Mercury is the smallest planet in our solar system.", "answer": "True"},
  {"text": "The Sahara is the coldest desert on Earth.", "answer": "False"},
  {"text": "Bamboo is the fastest-growing plant.", "answer": "True"},
  {"text": "The human tongue has different zones for taste types.", "answer": "False"},
  {"text": "Penguins live in the Arctic.", "answer": "False"},
  {"text": "The speed of light is faster than the speed of sound.", "answer": "True"},
  {"text": "All mammals lay eggs.", "answer": "False"},
  {"text": "The chemical formula of water is H2O.", "answer": "True"},
  {"text": "Jupiter is known as the Red Planet.", "answer": "False"},
  {"text": "The human heart has four chambers.", "answer": "True"},
  {"text": "Neutron stars are so dense that a sugar-cube sized amount would weigh billions of tons.", "answer": "True"},
  {"text": "The Andromeda Galaxy is moving away from the Milky Way.", "answer": "False"},
  {"text": "Quantum entanglement allows particles to affect each other instantly over any distance.", "answer": "True"},
  {"text": "DNA stands for Deoxyribonucleic Acid.", "answer": "True"},
  {"text": "Absolute zero is the hottest possible temperature.", "answer": "False"},
  {"text": "Antarctica is considered a desert.", "answer": "True"},
  {"text": "The strong nuclear force is weaker than the gravitational force.", "answer": "False"},
  {"text": "The Amazon Rainforest produces 20% of Earth's oxygen.", "answer": "False"},
  {"text": "Tungsten has the highest melting point of all pure metals.", "answer": "True"},
  {"text": "Prokaryotic cells contain a nucleus.", "answer": "False"}
]